### PR TITLE
Update impact table: Pagination & Search

### PR DESCRIPTION
**Pull request by eevan7a9**

### CODE REVIEW

**Comment by armanyan** [comment]
@eevan7a9 good work. Could you also apply the same filter to the impact tables on the `Lockdown` and `School Closure` pages please?

**Comment by eevan7a9** [comment]
I don't understand the Lockdown & School CLosure already has a filter.

**Comment by armanyan** [comment]
> @armanyan I don't understand. the Lockdown & School CLosure already has a filter.

In both lockdown and school closure pages, we have 2 tables, one is lockdown/school closure table (they have filters), and the other is impacts table (these don't have it).

**Comment by eevan7a9** [comment]
yes, I understand now. I'll add them.

**Pull request closed without merging**
